# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f29c1ad811147dc07e21eeb1550b93d5425ae75f4b3607fac2a5ac8fa87cb9c2db28d4e56d06df78a37266530fd3ceaffe75649b6f4085176122ea9e7af3ea10

test:
  secret_key_base: 6e658930fae38a8e4691d022297338a21f4714e311173a6861f7a5eae1b9b0e2d59600a34c80b4ce0ec768b707eefb5196d729cf497eac3acb2ae0bbffaa2a75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
